MODEL_DIRECTORY = 'models'

IMAGE_HEIGHT = 490
IMAGE_WIDTH = 640
# Can be scaled down by 2, 5 or 10
SCALE_FACTOR = 10

ROWS = int(IMAGE_HEIGHT/SCALE_FACTOR)
COLS = int(IMAGE_WIDTH/SCALE_FACTOR)

# Model Hyperparameters
NO_OF_FEATURES = 64
NO_OF_LABELS = 7
BATCH_SIZE = 64
NO_OF_EPOCHS = 1